# Netlify configuration for dYdX Trading Bot "WolfHunt"

[build]
  # Build command for the frontend
  command = "npm run build"
  
  # Base directory where package.json and vite.config.ts are located
  base = "frontend"
  
  # Directory to publish (output of React build)
  publish = "dist"
  
  # Functions directory (if using Netlify Functions)
  functions = "../netlify/functions"

# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# API proxy using Netlify Functions (more reliable than redirects)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/*"
  status = 200

# Redirect rules for SPA routing - catch-all MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# WebSocket proxy (if needed)
[[redirects]]
  from = "/ws/*"
  to = "wss://your-backend-url.com/ws/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML with shorter duration
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# CSP for enhanced security - Allow localhost in development
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https: wss: http://localhost:* ws://localhost:*;
      frame-ancestors 'none';
    """

# Form handling (if you have contact forms)
# [[plugins]]
#   package = "@netlify/plugin-forms"

# Edge functions directory (if using)
# [build]
#   edge_functions = "netlify/edge-functions"

# Deploy previews configuration
[context.deploy-preview]
  command = "cd frontend && npm run build:preview"

# Branch deploys
[context.branch-deploy]
  command = "cd frontend && npm run build"

# Development context
[context.dev]
  command = "cd frontend && npm run dev"

# Site settings
[template.environment]
  REACT_APP_API_BASE_URL = "https://your-backend-api-url.com"
  REACT_APP_WS_URL = "wss://your-backend-api-url.com"
  REACT_APP_ENVIRONMENT = "production"